version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
            sleep 10; 
            mc alias set myminio http://minio:9000 minioadmin minioadmin && \
            mc mb myminio/mybucket && \
            mc policy set download myminio/mybucket
            "

volumes:
  minio-data:
